#!/bin/sh

# autostart
sxhkd &
~/.config/bspwm/polybar.sh &

# monitors
bspc monitor -d 1 2 3 4 5

# config
bspc config border_width              1
bspc config window_gap                8
bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

# colors
bspc config normal_border_color       "#000000"
bspc config active_border_color       "#000000"
bspc config focused_border_color      "#00ff00"
bspc config presel_feedback_color     "#111111"

# window rules
bspc rule -a Screenkey manage=off

