#!/bin/sh

# autostart
sxhkd &
"$XDG_CONFIG_HOME/bspwm/polybar.sh" &


# monitors
bspc monitor -d 1 2 3 4 5

# config
bspc config border_width                2
bspc config borderless_monocle          true
bspc config directional_focus_tightness low
bspc config gapless_monocle             true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config split_ratio                 0.5
bspc config window_gap                  0

# colors
bspc config active_border_color         "#000000"
bspc config focused_border_color        "#aa0000"
bspc config normal_border_color         "#222222"
bspc config presel_feedback_color       "#111111"

# window rules
bspc rule -a Screenkey manage=off
