#!/bin/sh

# install homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install cask
brew install cask

# install packages
brew cask install mactex-no-gui
brew install ack
brew install afl-fuzz
brew install binwalk
brew install calcurse
brew install cifer
brew install cmake
brew install cmatrix
brew install cmus
brew install coreutils
brew install dash
brew install editorconfig
brew install entr
brew install eye-d3
brew install ffmpeg
brew install figlet
brew install findutils
brew install fzf
brew install gcc
brew install gdb
brew install geoip
brew install ghc cabal-install
brew install git
brew install git-lfs
brew install gnu-sed
brew install gnupg
brew install go
brew install grep
brew install hashpump
brew install htop
brew install hugo
brew install hydra
brew install imagemagick
brew install inetutils
brew install john
brew install knock
brew install libomp
brew install mitmproxy
brew install moreutils
brew install neofetch
brew install neovim
brew install netpbm
brew install newsboat
brew install nikto
brew install nmap
brew install onefetch
brew install open-mpi
brew install openssh
brew install pandoc
brew install pngcheck
brew install proselint
brew install python
brew install radare2
brew install rust
brew install shellcheck
brew install socat
brew install speedtest-cli
brew install sqlmap
brew install task
brew install tasksh
brew install tcpflow
brew install tcpreplay
brew install tcptrace
brew install the_silver_searcher
brew install tmux
brew install tor
brew install transmission
brew install watch
brew install wget
brew install youtube-dl
brew install z3
brew install zsh
