# default WM
WM=bspwm

# replace WM with $1 if exists
[ -n "$1" ] && WM="$1"

# set correct display coordinates and parameters
( setup-displays &&
    # and then set wallpaper
    xwallpaper --zoom "$XDG_CACHE_HOME"/wallpaper ) &

# set cursor size, etc.
xrdb "$XDG_CONFIG_HOME"/xresources &

# increase color temperature at night
redshift &

# hide mouse when idle
unclutter --timeout 3 &

# enable transparency
xcompmgr &

# Caps_Lock is ctrl
setxkbmap -option ctrl:nocaps &

# but when pressed alone for less than 250ms Caps_Lock is Escape
xcape -t 250 -e '#66=Escape' &

# fix for java GUIs (ghidra) in non-reparenting WMs
export _JAVA_AWT_WM_NONREPARENTING=1 &

# screen standy never, suspend never, off after 30 minutes
# set key repeat delay to 400ms set rate to 30 keys per second
# disable screen blanking
xset \
    dpms 0 0 1800 \
    r rate 400 30 \
    s 0 \
    &

# start window manager
exec $WM

