redshift &   # decrease col temp at night
unclutter --timeout 3 &  # hide mouse when idle
xcompmgr &   # enable transparency

# Caps_Lock is ctrl
setxkbmap -option ctrl:nocaps &
# But when pressed alone for less than 250ms Caps_Lock is Escape
xcape -t 250 -e '#66=Escape' &

# disable screen blanking
xset s off &

# set wallpaper
xwallpaper --zoom "$XDG_CACHE_HOME"/wallpaper &

# fix for java GUIs (ghidra) in non-reparenting WMs
export _JAVA_AWT_WM_NONREPARENTING=1 &

# start window manager
exec xmonad

