unclutter &  # hide mouse when idle
xcompmgr &   # enable transparency

# set keyboard layout
setxkbmap -layout de \
    -option caps:escape &

# disable screen blanking
xset s off &

# set wallpaper
xwallpaper --zoom "$XDG_CACHE_HOME"/wallpaper &

# fix for java GUIs (ghidra) in non-reparenting WMs
export _JAVA_AWT_WM_NONREPARENTING=1

# start window manager
exec xmonad

