unclutter &  # hide mouse when idle
xcompmgr &   # enable transparency

# set keyboard layout
setxkbmap -layout de \
    -option caps:escape &

# disable screen blanking
xset s off &

# set wallpaper
xwallpaper --zoom "$XDG_CACHE_HOME"/wallpaper &

# start window manager
exec $WM

