[alias]
b = "build"
br = "build --release"
c = "check"
cl = "clippy"
f = "fetch"
r = "run"
rr = "run --release"
t = "test"

[install]
root = "/home/dom/.local"

[profile.release]
codegen-units = 1
lto = "fat"

